### PR TITLE
Add support for qmldir file syntax

### PR DESCRIPTION
**Pull request by Furkanzmc**

### CODE REVIEW

**Comment by peterhoeg** [comment]
I've completely overlooked this - my apologies. Are you planning on whipping things into shape for review?

**Comment by Furkanzmc** [comment]
It's alright, I thought you were no longer maintaining the project so I switched to my own branch. I think I'll keep my branch for a while to see nothing broke, and then re-open this PR if you are still interested in merging the PR.

**Comment by peterhoeg** [comment]
I haven't used vim in years, but I do merge the occational PR as people seem to be using the repo.

If you have an actively maintained fork, I'll update the README to point to that instead.

**Comment by Furkanzmc** [comment]
If you can still merge PRs, project can stay here. `vim-polyglot` also links to this one so I may end up having to update a few things. Besides, you are the original author and as long as PRs are merged, this should probably be the main repository. Thank you.

**Pull request closed without merging**
