### PR TITLE
Improve Highlighting of QML Types and Properties

### PR DESCRIPTION
**Pull request by pl-energid**

### CODE REVIEW

**Comment by peterhoeg** [comment]
Why did you close this again @pl-energid ?

**Comment by pl-energid** [comment]
There was more work needed. (Attached properties were no longer highlighted properly, among other things).

**Comment by pl-energid** [comment]
With the latest state of my branch, the changes are large enough (e.g. removal of keyword highlighting for standard QML components, new highlighting for item ids and slots) that I was not sure if you would accept them, so I avoided creating a new pull request.

**Comment by peterhoeg** [comment]
I suggest to break it down into smaller pieces and we can then reach out to the various other contributors for input.

**Pull request closed without merging**
