### PR TITLE
Add new QML types

### PR DESCRIPTION
**Pull request by Furkanzmc**
- Added lists of QML types from the official docs
- Moved const to `qmlIdentifier`
- Added new identifiers from the documentation
- Added `let` as an identifier

### CODE REVIEW

**Comment by Furkanzmc** [comment]
One issue that I don't know how to solve is how to prevent the type colors from taking over the property colors.

qml_syntax

**Comment by peterhoeg** [comment]
Thank you for this. Much better than before despite the types overwriting the properties. Have you by chance tried changing the order to see if that solves anything?

**Comment by Furkanzmc** [comment]
I tried it now. It doesn't seem to work. I'll research this a bit later to try to solve it.

**Comment by peterhoeg** [comment]
@Furkanzmc did you manage to find anything?

**Comment by Furkanzmc** [comment]
Hi Peter.

Sorry, I completely forgot about this PR. I haven't had time to look into it.
In order to close the PR, I can fix the conflict and we can merge it as it is If you like. Then I'll create a separate PR to fix the previously mentioned problem. 

How would you like to proceed?

**Comment by peterhoeg** [comment]
Sounds great, let's do that!

**Comment by Furkanzmc** [comment]
OK. I updated the type list from the documentation for v5.15.1. I've been wanting to delve more into the syntax in Vim, so I'll look into how I can resolve the problem.

Thanks, Peter!

**Comment by peterhoeg** [comment]
Thank you for the contribution!

**Pull request merged**
